In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle
import numpy as np


import datetime

In [2]:
df = pd.read_csv("Churn_Modelling.csv")

In [3]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
df = df.drop(["RowNumber", "CustomerId", "Surname"], axis = 1)

In [8]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
label_encoder_gender = LabelEncoder()
df["Gender"] = label_encoder_gender.fit_transform(df["Gender"])

In [10]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [11]:
onehot_encoder_geo = OneHotEncoder()

geo_encoder = onehot_encoder_geo.fit_transform(df[["Geography"]])

In [12]:
geo_encoder
onehot_encoder_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [13]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns = onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
df = pd.concat([df.drop("Geography" , axis = 1), geo_encoded_df], axis = 1)

In [15]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [16]:
## Save the encoder and scaler as pickel files

with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender, file)
with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(onehot_encoder_geo, file)

In [17]:
## Dependent and independernt eatures

X = df.drop("Exited", axis = 1)
y = df["Exited"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

##scale

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
X.shape

(10000, 12)

In [19]:
with open("scaler.pkl", "wb") as file:

    pickle.dump(scaler, file)

In [20]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [21]:
X_train_tensor = torch.tensor(X_train, dtype = torch.float32)
X_test_tensor = torch.tensor(X_test, dtype = torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype = torch.float).view(-1, 1)
y_test_tensor = torch.tensor(y_test.values, dtype = torch.float).view(-1, 1)

In [22]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = False)

In [23]:
class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__() 
        self.model = nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),

            
            nn.Linear(64, 1)           
                                    
            
        )

    def forward(self, x):
        return self.model(x)

In [24]:
from torch.utils.tensorboard import SummaryWriter
import datetime
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
writer = SummaryWriter("logs/fit")

In [25]:
model = ANN()
model = model
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters())

In [26]:
epochs = 100

for epoch in range(epochs):

    # TRAIN 
    model.train()

    correct = 0
    total = 0
    running_loss = 0

    for xb, yb in train_loader:

        optimizer.zero_grad()

        pred = model(xb)

        loss = criterion(pred, yb)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        predicted = (torch.sigmoid(pred) >= 0.5).float()

        total += yb.size(0)
        correct += (predicted == yb).sum().item()

    train_accuracy = correct / total
    train_loss = running_loss / len(train_loader)


    # VALIDATION 
    model.eval()

    correct = 0
    total = 0
    val_running_loss = 0

    with torch.no_grad():

        for xb, yb in test_loader:

            outputs = model(xb)

            loss = criterion(outputs, yb)

            val_running_loss += loss.item()

            predicted = (torch.sigmoid(outputs) >= 0.5).float()

            total += yb.size(0)
            correct += (predicted == yb).sum().item()

    val_accuracy = correct / total
    val_loss = val_running_loss / len(test_loader)


    # TENSORBOARD 

    writer.add_scalar("Loss/train", train_loss, epoch)
    writer.add_scalar("Loss/validation", val_loss, epoch)

    writer.add_scalar("Accuracy/train", train_accuracy, epoch)
    writer.add_scalar("Accuracy/validation", val_accuracy, epoch)
    


    print(
        f"Epoch {epoch+1}/{epochs} "
        f"Train Loss: {train_loss} "
        f"Train Acc: {train_accuracy}  "
        f"Val Loss: {val_loss} "
        f"Val Acc: {val_accuracy}"
    )

Epoch 1/100 Train Loss: 0.46232793855667115 Train Acc: 0.7975  Val Loss: 0.40522796459614285 Val Acc: 0.8265
Epoch 2/100 Train Loss: 0.39189824187755584 Train Acc: 0.834125  Val Loss: 0.3558107649996167 Val Acc: 0.8555
Epoch 3/100 Train Loss: 0.3539856895804405 Train Acc: 0.854875  Val Loss: 0.34187826537896715 Val Acc: 0.865
Epoch 4/100 Train Loss: 0.3439822296500206 Train Acc: 0.859625  Val Loss: 0.342754905659055 Val Acc: 0.861
Epoch 5/100 Train Loss: 0.34029211980104446 Train Acc: 0.8585  Val Loss: 0.340502158989982 Val Acc: 0.8575
Epoch 6/100 Train Loss: 0.3362689583301544 Train Acc: 0.859  Val Loss: 0.3441753370894326 Val Acc: 0.857
Epoch 7/100 Train Loss: 0.3339149565398693 Train Acc: 0.861375  Val Loss: 0.34631302834503236 Val Acc: 0.8605
Epoch 8/100 Train Loss: 0.3329852677285671 Train Acc: 0.861  Val Loss: 0.34355616711434867 Val Acc: 0.858
Epoch 9/100 Train Loss: 0.3316435681283474 Train Acc: 0.86325  Val Loss: 0.34338625863430994 Val Acc: 0.8655
Epoch 10/100 Train Loss: 0.32805095812678337 Train Acc: 0.864  Val Loss: 0.34504634520364186 Val Acc: 0.8625
Epoch 11/100 Train Loss: 0.3264907774925232 Train Acc: 0.86475  Val Loss: 0.341006680376946 Val Acc: 0.862
Epoch 12/100 Train Loss: 0.32497852233052255 Train Acc: 0.86675  Val Loss: 0.3403475894814446 Val Acc: 0.859
Epoch 13/100 Train Loss: 0.3235115402042866 Train Acc: 0.867875  Val Loss: 0.3382295133575561 Val Acc: 0.864
Epoch 14/100 Train Loss: 0.32276339703798296 Train Acc: 0.866875  Val Loss: 0.3389819460728812 Val Acc: 0.864
Epoch 15/100 Train Loss: 0.31906209540367125 Train Acc: 0.866625  Val Loss: 0.3443227147772199 Val Acc: 0.8615
Epoch 16/100 Train Loss: 0.31926290738582613 Train Acc: 0.868625  Val Loss: 0.34005791421920534 Val Acc: 0.8635
Epoch 17/100 Train Loss: 0.31677668753266336 Train Acc: 0.868125  Val Loss: 0.3394519632297849 Val Acc: 0.8645
Epoch 18/100 Train Loss: 0.3137135130763054 Train Acc: 0.8695  Val Loss: 0.33782745945075204 Val Acc: 0.8625
Epoch 19/100 Train Loss: 0.31333667370676993 Train Acc: 0.869875  Val Loss: 0.34266505094747696 Val Acc: 0.8585
Epoch 20/100 Train Loss: 0.31213489729166033 Train Acc: 0.87225  Val Loss: 0.34520844571174136 Val Acc: 0.8595
Epoch 21/100 Train Loss: 0.3110859079658985 Train Acc: 0.872125  Val Loss: 0.3397274154519278 Val Acc: 0.8675
Epoch 22/100 Train Loss: 0.3093362102508545 Train Acc: 0.870375  Val Loss: 0.3454719346667093 Val Acc: 0.863
Epoch 23/100 Train Loss: 0.30754785796999934 Train Acc: 0.87275  Val Loss: 0.3419271880199039 Val Acc: 0.86
Epoch 24/100 Train Loss: 0.30703312945365907 Train Acc: 0.87125  Val Loss: 0.34474769565794205 Val Acc: 0.8585
Epoch 25/100 Train Loss: 0.3056381159424782 Train Acc: 0.874125  Val Loss: 0.3419103338604882 Val Acc: 0.858
Epoch 26/100 Train Loss: 0.3041609824895859 Train Acc: 0.8735  Val Loss: 0.34486098540207694 Val Acc: 0.866
Epoch 27/100 Train Loss: 0.3010861045122147 Train Acc: 0.875  Val Loss: 0.34609190552007585 Val Acc: 0.8605
Epoch 28/100 Train Loss: 0.30075754135847094 Train Acc: 0.873875  Val Loss: 0.3430970665954408 Val Acc: 0.8625
Epoch 29/100 Train Loss: 0.2997664310336113 Train Acc: 0.872625  Val Loss: 0.34797603767069557 Val Acc: 0.8565
Epoch 30/100 Train Loss: 0.29897241258621216 Train Acc: 0.873375  Val Loss: 0.3462269367679717 Val Acc: 0.864
Epoch 31/100 Train Loss: 0.2984009742736816 Train Acc: 0.875875  Val Loss: 0.3483617918358909 Val Acc: 0.855
Epoch 32/100 Train Loss: 0.29541185691952704 Train Acc: 0.878625  Val Loss: 0.3536801122956806 Val Acc: 0.8575
Epoch 33/100 Train Loss: 0.2965218343436718 Train Acc: 0.87725  Val Loss: 0.34718031211504863 Val Acc: 0.8595
Epoch 34/100 Train Loss: 0.29303429698944095 Train Acc: 0.879  Val Loss: 0.35147253577671356 Val Acc: 0.8645
Epoch 35/100 Train Loss: 0.29259037086367606 Train Acc: 0.877125  Val Loss: 0.35237011549964786 Val Acc: 0.862
Epoch 36/100 Train Loss: 0.29136299750208855 Train Acc: 0.878375  Val Loss: 0.3513332912846217 Val Acc: 0.8565
Epoch 37/100 Train Loss: 0.28935665157437324 Train Acc: 0.879375  Val Loss: 0.3574101723848827 Val Acc: 0.853
Epoch 38/100 Train Loss: 0.2895126594901085 Train Acc: 0.87725  Val Loss: 0.35192868799444227 Val Acc: 0.852
Epoch 39/100 Train Loss: 0.2885154517591 Train Acc: 0.87875  Val Loss: 0.36061392771819284 Val Acc: 0.8585
Epoch 40/100 Train Loss: 0.287243513405323 Train Acc: 0.879125  Val Loss: 0.3533419403764937 Val Acc: 0.86
Epoch 41/100 Train Loss: 0.2837436000406742 Train Acc: 0.8805  Val Loss: 0.3557386135771161 Val Acc: 0.856
Epoch 42/100 Train Loss: 0.2854155635237694 Train Acc: 0.880375  Val Loss: 0.35914922493790824 Val Acc: 0.8555
Epoch 43/100 Train Loss: 0.28394822600483893 Train Acc: 0.880375  Val Loss: 0.3578313442449721 Val Acc: 0.8585
Epoch 44/100 Train Loss: 0.2825924005508423 Train Acc: 0.883875  Val Loss: 0.3581408891412947 Val Acc: 0.8555
Epoch 45/100 Train Loss: 0.28002379125356675 Train Acc: 0.881125  Val Loss: 0.36115519749739816 Val Acc: 0.852
Epoch 46/100 Train Loss: 0.27927100160717966 Train Acc: 0.881875  Val Loss: 0.3627533650114423 Val Acc: 0.854
Epoch 47/100 Train Loss: 0.2794510564506054 Train Acc: 0.881  Val Loss: 0.37329782569219194 Val Acc: 0.855
Epoch 48/100 Train Loss: 0.27727825289964675 Train Acc: 0.883375  Val Loss: 0.36784418967981186 Val Acc: 0.8585
Epoch 49/100 Train Loss: 0.2758225589990616 Train Acc: 0.88325  Val Loss: 0.37348856552252696 Val Acc: 0.848
Epoch 50/100 Train Loss: 0.27493824090063573 Train Acc: 0.88375  Val Loss: 0.36690684135944124 Val Acc: 0.852
Epoch 51/100 Train Loss: 0.27354763907194135 Train Acc: 0.882875  Val Loss: 0.3771789828463206 Val Acc: 0.845
Epoch 52/100 Train Loss: 0.2739434642493725 Train Acc: 0.884  Val Loss: 0.37739306782919263 Val Acc: 0.855
Epoch 53/100 Train Loss: 0.27217142122983934 Train Acc: 0.88525  Val Loss: 0.38214985458623796 Val Acc: 0.8395
Epoch 54/100 Train Loss: 0.2730883894264698 Train Acc: 0.883875  Val Loss: 0.36909627867123435 Val Acc: 0.855
Epoch 55/100 Train Loss: 0.2688333249390125 Train Acc: 0.88725  Val Loss: 0.3824817292273991 Val Acc: 0.854
Epoch 56/100 Train Loss: 0.2682042309343815 Train Acc: 0.88775  Val Loss: 0.3834264663949845 Val Acc: 0.8395
Epoch 57/100 Train Loss: 0.26766535446047784 Train Acc: 0.88475  Val Loss: 0.3785378336906433 Val Acc: 0.856
Epoch 58/100 Train Loss: 0.2654828692674637 Train Acc: 0.88825  Val Loss: 0.38770742312310236 Val Acc: 0.846
Epoch 59/100 Train Loss: 0.2653792674839497 Train Acc: 0.88675  Val Loss: 0.3863339563683858 Val Acc: 0.8495
Epoch 60/100 Train Loss: 0.26485523319244386 Train Acc: 0.887875  Val Loss: 0.38028064606681705 Val Acc: 0.852
Epoch 61/100 Train Loss: 0.26328338000178336 Train Acc: 0.886875  Val Loss: 0.3845362961292267 Val Acc: 0.8535
Epoch 62/100 Train Loss: 0.26174979776144025 Train Acc: 0.88875  Val Loss: 0.3925751241899672 Val Acc: 0.8435
Epoch 63/100 Train Loss: 0.26229826495051384 Train Acc: 0.888125  Val Loss: 0.3876566297951199 Val Acc: 0.852
Epoch 64/100 Train Loss: 0.26042934486269953 Train Acc: 0.889  Val Loss: 0.39670088792604113 Val Acc: 0.8355
Epoch 65/100 Train Loss: 0.2599965590536594 Train Acc: 0.889125  Val Loss: 0.388203506195356 Val Acc: 0.848
Epoch 66/100 Train Loss: 0.2583601699471474 Train Acc: 0.89  Val Loss: 0.40377010286800447 Val Acc: 0.837
Epoch 67/100 Train Loss: 0.25721358534693717 Train Acc: 0.8905  Val Loss: 0.3933578845527437 Val Acc: 0.852
Epoch 68/100 Train Loss: 0.25612633273005486 Train Acc: 0.892625  Val Loss: 0.3965128731159937 Val Acc: 0.848
Epoch 69/100 Train Loss: 0.2555237638056278 Train Acc: 0.890625  Val Loss: 0.40049791194143747 Val Acc: 0.849
Epoch 70/100 Train Loss: 0.25471604156494143 Train Acc: 0.891375  Val Loss: 0.3953388858409155 Val Acc: 0.847
Epoch 71/100 Train Loss: 0.2522851632833481 Train Acc: 0.893  Val Loss: 0.4158314090399515 Val Acc: 0.831
Epoch 72/100 Train Loss: 0.25325740087032317 Train Acc: 0.89025  Val Loss: 0.4049264384167535 Val Acc: 0.848
Epoch 73/100 Train Loss: 0.25233800646662713 Train Acc: 0.890125  Val Loss: 0.40634466281958986 Val Acc: 0.846
Epoch 74/100 Train Loss: 0.24861730423569678 Train Acc: 0.896125  Val Loss: 0.4001866588516841 Val Acc: 0.838
Epoch 75/100 Train Loss: 0.24898813790082933 Train Acc: 0.894875  Val Loss: 0.40492942716394154 Val Acc: 0.8435
Epoch 76/100 Train Loss: 0.24760637286305429 Train Acc: 0.89525  Val Loss: 0.40269139338107335 Val Acc: 0.8475
Epoch 77/100 Train Loss: 0.249962290674448 Train Acc: 0.893875  Val Loss: 0.4044688455169163 Val Acc: 0.8445
Epoch 78/100 Train Loss: 0.24689944621920584 Train Acc: 0.894125  Val Loss: 0.4064374726916116 Val Acc: 0.8465
Epoch 79/100 Train Loss: 0.24533422508835792 Train Acc: 0.89475  Val Loss: 0.40414106018013424 Val Acc: 0.8425
Epoch 80/100 Train Loss: 0.24321967151761054 Train Acc: 0.894625  Val Loss: 0.4127624228833214 Val Acc: 0.842
Epoch 81/100 Train Loss: 0.24389092254638672 Train Acc: 0.895875  Val Loss: 0.4103565840494065 Val Acc: 0.8505
Epoch 82/100 Train Loss: 0.24375250360369682 Train Acc: 0.894125  Val Loss: 0.413122749281308 Val Acc: 0.8435
Epoch 83/100 Train Loss: 0.24208848710358144 Train Acc: 0.897125  Val Loss: 0.42288809707240455 Val Acc: 0.8365
Epoch 84/100 Train Loss: 0.24232522377371787 Train Acc: 0.897875  Val Loss: 0.42077320009943037 Val Acc: 0.8425
Epoch 85/100 Train Loss: 0.241759878590703 Train Acc: 0.896375  Val Loss: 0.41563473405346035 Val Acc: 0.8435
Epoch 86/100 Train Loss: 0.23989652049541474 Train Acc: 0.897625  Val Loss: 0.42194880781665683 Val Acc: 0.84
Epoch 87/100 Train Loss: 0.23856041899323463 Train Acc: 0.89825  Val Loss: 0.4303318380363404 Val Acc: 0.8365
Epoch 88/100 Train Loss: 0.24112549501657485 Train Acc: 0.900125  Val Loss: 0.4325716221143329 Val Acc: 0.8375
Epoch 89/100 Train Loss: 0.23860561165213584 Train Acc: 0.8965  Val Loss: 0.4246397243132667 Val Acc: 0.8405
Epoch 90/100 Train Loss: 0.23661609396338462 Train Acc: 0.897375  Val Loss: 0.4251671882848891 Val Acc: 0.8455
Epoch 91/100 Train Loss: 0.23540762171149254 Train Acc: 0.89825  Val Loss: 0.4244207574261559 Val Acc: 0.8485
Epoch 92/100 Train Loss: 0.23528317907452584 Train Acc: 0.90275  Val Loss: 0.425392806056946 Val Acc: 0.8425
Epoch 93/100 Train Loss: 0.23334528525173664 Train Acc: 0.9025  Val Loss: 0.4304099806717464 Val Acc: 0.846
Epoch 94/100 Train Loss: 0.23390974090993405 Train Acc: 0.8995  Val Loss: 0.43161524926859235 Val Acc: 0.845
Epoch 95/100 Train Loss: 0.2323367664515972 Train Acc: 0.90175  Val Loss: 0.43693786386459593 Val Acc: 0.845
Epoch 96/100 Train Loss: 0.23149565137922765 Train Acc: 0.900625  Val Loss: 0.42943225280633046 Val Acc: 0.841
Epoch 97/100 Train Loss: 0.23002159658074378 Train Acc: 0.90175  Val Loss: 0.4345270558482125 Val Acc: 0.851
Epoch 98/100 Train Loss: 0.23155207207798958 Train Acc: 0.89825  Val Loss: 0.43475224929196493 Val Acc: 0.838
Epoch 99/100 Train Loss: 0.2276743306070566 Train Acc: 0.903  Val Loss: 0.43733210152103785 Val Acc: 0.835
Epoch 100/100 Train Loss: 0.22882603748142719 Train Acc: 0.902  Val Loss: 0.4335439067984384 Val Acc: 0.8435

In [27]:
torch.save(model.state_dict(), "ann_model.pth")

In [28]:
%load_ext tensorboard

In [29]:
%tensorboard --logdir logs/fit --port 6004

Reusing TensorBoard on port 6004 (pid 14832), started 5:52:48 ago. (Use '!kill 14832' to kill it.)